development:
  adapter: postgresql
  database: profcyn_simple_rails_development
  password: 
  encoding: utf8
  host: localhost
  
test:
  adapter: postgresql
  database: profcyn_simple_rails_development
  password: 
  encoding: utf8
  host: localhost
  
production:
  adapter: postgresql
  database: profcyn_simple_rails_development
  password: 
  encoding: utf8
  host: localhost
